export const STUDENT_ASSESSMENTS_REQUEST = "TEACHER_ASSESSMENTS_REQUEST"
export const STUDENT_ASSESSMENTS_SUCCESS = "TEACHER_ASSESSMENTS_SUCCESS"
export const STUDENT_ASSESSMENTS_FAIL = "TEACHER_ASSESSMENTS_FAIL"